### ISSUE TITLE
Document the single-subject resampling and merging

### ISSUE THREAD

**Issue by robertoostenveld** [SIESTA-eu/wp15#51]
We want single-subject pipelines to run on single-subject datasets. The pseudo option in `BIDScramble` can make those single-subject versions; this needs to be documented in the README for each of the use cases. 

Following the single-subject pipelines, the derivative data needs to be merged. This requires looking into the different use cases, as they differ in how intermediate or derivative data is organized. E.g., 2.1 does not have single-subject intermediate data, and 2.5 uses SPM which results in some intermediate/derivative data (not according to BIDS specification) to end up in the same directory as the input data.

**Comment by marcelzwiers** [comment]
The reason why single subject scrambling was not working for usecase 2.1 was because all the sub-directories were empty. If I first make a stub then it all works, in this for `sub-03`:

```console
# Loop through all sub-* directories inside input and create a placeholder file
for dir in input/sub-*; do
    if [[ -d "$dir" ]]; then
        folder_name=$(basename "$dir")
        touch "$dir/${folder_name}_placeholder.txt" 
    fi
done

scramble ~/siesta/usecase-2.1/input/ keep1 pseudo original -s 'sub-03.*'
```

I'll see if I can do anything about empty sub-folders (as they are allowed), otherwise we can always run ` scramble inputdir outputdir stub`

**Comment by marcelzwiers** [comment]
Btw, in the case of the empty subject folders, the scrambler did say it didn't find any files (no files found was meant as a warning):
```
$ scramble ~/siesta/usecase-2.1/input/ keep1 pseudo original -s 'sub-03.*'
No files found in /project/3011231.02/siesta/usecase-2.1/input using 'sub-03.*'
Copying the data of 0 subjects to: /project/3015999.02/siesta/marzwi/keep1
```

**Comment by marcelzwiers** [comment]
I think we should keep a formal log, not sure what is the best way forward though (python has a logging library, but we may need something more general)

**Comment by marcelzwiers** [comment]
> I'll see if I can do anything about empty sub-folders (as they are allowed)

Fixed, the scrambler should work now with empty sub-folders as expected

**Comment by robertoostenveld** [comment]
in the limited version of the data that is downloaded with the 2.1 README instructions there are not even folders, only these files

```
input
├── CHANGES
├── dataset_description.json
├── participants.json
├── participants.tsv
└── README
```

I also tried to assist the scrambler by creating empty sub-xxx directories, but that (as you say) was not sufficient.

One solution is to have the scrambler deal with this specific dataset. But perhaps we should also consider dataset validity. 

If I pass the downloaded dataset through https://bids-standard.github.io/bids-validator/ then it is not valid due to "Participant labels found in this dataset did not match the values in participant_id column found in the participants.tsv file". 

if I do this

    for SUBJ in `seq -w 60`; do mkdir sub-$SUBJ; done  

it is still not valid, with the same error. 

if I do this 

    for SUBJ in `seq -w 60`; do mkdir sub-$SUBJ/anat ; done
    for SUBJ in `seq -w 60`; do touch sub-$SUBJ/anat/sub-"$SUBJ"_T1w.nii ; done

I get further with an "invalid nifti header" and a "empty files" error. So if those nii files were not empty (aka downloaded from the original dataset), I suppose it would work.

The question then is whether we should pose the requirement for BIDSscrambler that the input is valid or passes the validator (which is not guaranteed to be exactly the same, as both the spec and validator have imperfections). 

Could you run the validator on each of the 5 datasets that we have, i.e., on the datasets after downloading with the instructions that we provide in the README?

**Comment by marcelzwiers** [comment]
```
(venv) mentat007/marzwi$ tree /project/3011231.02/siesta/usecase-2.1/input/ | head -n 20
/project/3011231.02/siesta/usecase-2.1/input/
├── CHANGES
├── dataset_description.json
├── participants.json
├── participants.tsv
├── README
├── sub-01
├── sub-02
├── sub-03
├── sub-04
[..]
(venv) mentat007/marzwi$ scramble /project/3011231.02/siesta/usecase-2.1/input/ keep1 pseudo original -s 'sub-03(/|$).*'
WARNING: No files found in /project/3011231.02/siesta/usecase-2.1/input using 'sub-03(/|$).*'
Copying the data of 1 subjects to: /project/3015999.02/siesta/marzwi/keep1
--> /project/3015999.02/siesta/marzwi/keep1/participants.tsv                                                                                                                                                            
Pruning sub-01 record from /project/3015999.02/siesta/marzwi/keep1/participants.tsv
Pruning sub-02 record from /project/3015999.02/siesta/marzwi/keep1/participants.tsv
[..]
Pruning sub-59 record from /project/3015999.02/siesta/marzwi/keep1/participants.tsv
Pruning sub-60 record from /project/3015999.02/siesta/marzwi/keep1/participants.tsv
(venv) mentat007/marzwi$ tree keep1/
keep1/
├── CHANGES
├── dataset_description.json
├── participants.json
├── participants.tsv
├── README
└── sub-03
(venv) mentat007/marzwi$ wc -l keep1/participants.tsv 
2 keep1/participants.tsv
```
The participants file has a header and one subject row, as expected. If you remove the sub-folders, then the input is not BIDS-valid anymore and the scrambler doesn't understand what to do

**Comment by marcelzwiers** [comment]
I think you may need to re-installing bidsscramble like this:
```
pip install --no-deps --force-reinstall .
```

**Comment by robertoostenveld** [comment]
> > I also tried to assist the scrambler by creating empty sub-xxx directories, but that (as you say) was not sufficient.
>
> I cannot replicate that:

Oh sorry, that was yesterday after your updates. I have not tried yet today. 

If I now download the data according to instructions (or using the container) and run 

    scramble input keep1 pseudo original -s 'sub-03(/|$).*'

it still does not work. If I add the sub-xx directories, it does work 🎉😃. 

So the README and the download.sif still need to be updated in order for those directories to be created. I don't think that wget can be used for empty directories, but 

    for SUBJ in `seq -w 60`; do mkdir sub-${SUBJ} ; done

should do it. Can you update the README and container, and can you also add a section with resampling instructions to the README? I think that should work with

    for SUBJ in `seq -w 60`; do scramble input singlesubject-${SUBJ} pseudo original -s sub-${SUBJ}'(/|$).*' ; done

That should then be tested and documented in the README for all 5 use cases.

**Comment by marcelzwiers** [comment]
Like I said, if there are no sub-folders, it is too far away from the BIDS standard to work with. So we need to fix the input folder, not bidscramble

**Comment by marcelzwiers** [comment]
Actually, I made the scramble as generic as possible, meaning that all scamble "actions" work with non-BIDS data also. Except for "pseudo", which needs to know about the participant labels. Even that action is pretty tolerant for allowing non-BIDS data, but the one thing it needs is sub-folders (to parse the participant labels).

**Comment by robertoostenveld** [comment]
How "far away" from the BIDS standard would you find acceptable? Should we enforce compliance with the standard and implement validation in our [workflow](https://github.com/SIESTA-eu/wp15/blob/main/docs/workflow.md)? If we don't enforce strict compliance, then that should also be documented.

**Comment by marcelzwiers** [comment]
I'll document this more clearly, but like I said, thus far bidscramble can stretch a very long way
